pipeline {
    agent any

    environment {
        IMAGE_NAME = "nodejs-docker-app"
        CONTAINER_NAME = "nodejs-container"
    }

    stages {
        stage('Checkout') {
            steps {
                echo "Cloning source code from GitHub..."
                git branch: 'nodejs-docker-task', url: 'https://github.com/Mohamed-Elsayed-Hussein/Devops.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Docker/Session 3 Dockerize a Node.js Application') {
                    echo "Building Docker image from Dockerfile..."
                    sh "docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} ."
                }
            }
        }

        stage('Run Container') {
            steps {
                echo "Running Docker container..."
                script {
                    // Stop & remove old container if exists
                    sh """
                    if [ \$(docker ps -aq -f name=${CONTAINER_NAME}) ]; then
                        docker stop ${CONTAINER_NAME} || true
                        docker rm ${CONTAINER_NAME} || true
                    fi
                    """
                    // Run the new container
                    sh "docker run -d --name ${CONTAINER_NAME} -p 3000:3000 ${IMAGE_NAME}:latest"
                }
            }
        }
    }

    post {
        success {
            echo "✅ App deployed successfully on port 3000."
        }
        failure {
            echo "❌ Pipeline failed! Check logs for details."
        }
    }
}

